apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nodejs.yaml
  - mysql.yaml
  - redis.yaml
  - ingress.yaml
images:
  - name: 481665092783.dkr.ecr.eu-central-1.amazonaws.com/nodejs-app
    newTag: v4
